
-- https://jira.machado.com.br/browse/ESICAM-698
ALTER TABLE HISTORICO_STATUS_MAT_COL_ENVIO MODIFY DS_JUSTIFICATIVA DEFAULT NULL NULL;
-- fim ESICAM-698

-- https://jira.machado.com.br/browse/ESICAM-706
INSERT INTO SICAM.STATUS_MATERIAL_COLETA_ENVIO (DE_STATUS_MATERIAL_COLETA) VALUES ('Alteração de Condição do Bem');
INSERT INTO SICAM.STATUS_MATERIAL_COLETA_ENVIO (DE_STATUS_MATERIAL_COLETA) VALUES ('Inclusão de Número de Tombo');
-- fim ESICAM-706

-- https://jira.machado.com.br/browse/ESICAM-729

ALTER TABLE SICAM.AUDITORIA  RENAME COLUMN TP_OPERACAO TO TI_OPERACAO;
ALTER TABLE SICAM.AUDITORIA  RENAME COLUMN DT_OPERACAO TO TS_OPERACAO;

ALTER TABLE SICAM.COLETA RENAME COLUMN DT_COLETA TO TS_COLETA;
ALTER TABLE SICAM.COLETA RENAME COLUMN NU_LOTACAO TO CO_LOTACAO;

ALTER TABLE SICAM.CONSOLIDACAO_FINAL RENAME COLUMN DT_CONSOLIDACAO TO TS_CONSOLIDACAO;

ALTER TABLE SICAM.CONSOLIDACAO_LOTACAO RENAME COLUMN DT_CONSOLIDACAO TO TS_CONSOLIDACAO;

ALTER TABLE SICAM.HISTORICO_COLETA_STATUS RENAME COLUMN DT_STATUS TO   TS_STATUS;

ALTER TABLE SICAM.HISTORICO_ENVIO_COLETA RENAME COLUMN DT_ENVIO TO  TS_ENVIO;

ALTER TABLE SICAM.HISTORICO_OPERACAO RENAME COLUMN TP_OPERACAO TO   TI_OPERACAO;
ALTER TABLE SICAM.HISTORICO_OPERACAO RENAME COLUMN DT_OPERACAO TO   TS_OPERACAO;
ALTER TABLE SICAM.HISTORICO_OPERACAO RENAME COLUMN DS_VALOR_COLUNA TO   DE_VALOR_COLUNA;
ALTER TABLE SICAM.HISTORICO_OPERACAO RENAME COLUMN DS_JUSTIFICATIVA TO   DE_JUSTIFICATIVA;

ALTER TABLE SICAM.HISTORICO_STATUS_CONSOL_FINAL RENAME COLUMN DT_STATUS TO TS_STATUS;

ALTER TABLE SICAM.HISTORICO_STATUS_CONSOL_LOTACA RENAME COLUMN DT_STATUS TO TS_STATUS;

ALTER TABLE SICAM.HISTORICO_STATUS_ENVIO_COLETA RENAME COLUMN DT_STATUS TO TS_STATUS;
ALTER TABLE SICAM.HISTORICO_STATUS_ENVIO_COLETA RENAME COLUMN DS_JUSTIFICATIVA TO DE_JUSTIFICATIVA;

ALTER TABLE SICAM.HISTORICO_STATUS_MAT_COL_ENVIO RENAME COLUMN DT_STATUS TO TS_STATUS;
ALTER TABLE SICAM.HISTORICO_STATUS_MAT_COL_ENVIO RENAME COLUMN DS_JUSTIFICATIVA TO DE_JUSTIFICATIVA;

ALTER TABLE SICAM.INVENTARIO RENAME COLUMN NU_LOTACAO TO CO_LOTACAO;
ALTER TABLE SICAM.INVENTARIO ADD ANO_REFERENCIA NUMBER(4);
UPDATE SICAM.INVENTARIO SET ANO_REFERENCIA=TO_NUMBER(NU_ANO_REFERENCIA);
COMMIT;
ALTER TABLE SICAM.INVENTARIO DROP COLUMN NU_ANO_REFERENCIA;

ALTER TABLE SICAM.LOTACAO_ANUENCIA RENAME COLUMN DT_ANUENCIA TO    TS_ANUENCIA;

ALTER TABLE SICAM.MATERIAL_COLETA RENAME COLUMN NU_LOTACAO TO    CO_LOTACAO;
ALTER TABLE SICAM.MATERIAL_COLETA RENAME COLUMN DT_COLETA_MATERIAL TO    TS_COLETA_MATERIAL;
ALTER TABLE SICAM.MATERIAL_COLETA RENAME COLUMN DT_ULTIMA_ALTERACAO TO    TS_ULTIMA_ALTERACAO;

ALTER TABLE SICAM.MEMBRO_AUXILIAR_LOTACAO RENAME COLUMN NU_LOTACAO TO  CO_LOTACAO;
ALTER TABLE SICAM.MEMBRO_AUXILIAR_LOTACAO RENAME COLUMN DT_ASSOCIACAO TO  TS_ASSOCIACAO;
ALTER TABLE SICAM.MEMBRO_AUXILIAR_LOTACAO RENAME COLUMN DS_JUSTIFICATIVA TO  DE_JUSTIFICATIVA;
ALTER TABLE SICAM.MEMBRO_AUXILIAR_LOTACAO RENAME COLUMN DT_CANCELAMENTO TO  TS_CANCELAMENTO;

ALTER TABLE SICAM.MEMBRO_INVENTARIO RENAME COLUMN  DT_VINCULACAO TO   TS_VINCULACAO;
ALTER TABLE SICAM.MEMBRO_INVENTARIO RENAME COLUMN  DS_JUSTIFICATIVA TO   DE_JUSTIFICATIVA;
ALTER TABLE SICAM.MEMBRO_INVENTARIO RENAME COLUMN  TP_OPERACAO TO   TI_OPERACAO;

ALTER TABLE SICAM.NOTIFICACAO RENAME COLUMN DT_NOTIFICACAO TO TS_NOTIFICACAO;
ALTER TABLE SICAM.NOTIFICACAO RENAME COLUMN DT_CIENCIA_NOTIFICACAO TO TS_CIENCIA_NOTIFICACAO;

ALTER TABLE SICAM.CONSOLIDACAO_COLETA RENAME COLUMN NU_CONSOLIDACAO TO NU_CONSOLIDACAO_LOTACAO;

ALTER TABLE SICAM.QUESTAO_RELATORIO RENAME COLUMN  DS_QUESTAO_RELATORIO TO  DE_QUESTAO_RELATORIO ;

CREATE OR REPLACE VIEW SICAM.VW_HISTORICO_TRAMITE_COLETA
(ID,NU_HISTORICO_COLETA_STATUS,TS_HISTORICO,NU_STATUS_COLETA,NU_COLETA,NU_MATRICULA,DE_JUSTIFICATIVA)
AS
SELECT
  ROWNUM          as ID,
  SH.NU_HISTORICO_COLETA_STATUS,
  SH.TS_STATUS    AS DT_HISTORICO,
  SH.NU_STATUS_COLETA,
  SH.NU_COLETA,
  SH.NU_MATRICULA,
  case
    when SH.NU_STATUS_COLETA = 2 then (
        select
               LISTAGG('('||hsec.NU_MATRICULA || ' - ' || to_char(hsec.TS_STATUS, 'DD/MM/YYYY HH24:MM:SS') || ') ' || hsec.DE_JUSTIFICATIVA, '; ')
                   WITHIN GROUP (ORDER BY TS_STATUS desc)
        from SICAM.HISTORICO_ENVIO_COLETA C
               join SICAM.HISTORICO_STATUS_ENVIO_COLETA hsec
                 on C.NU_HISTORICO_ENVIO = hsec.NU_HISTORICO_ENVIO
           where c.NU_COLETA = SH.nu_coleta
             and SH.TS_STATUS = c.TS_ENVIO
                                      )
    else null end as DE_JUSTIFICATIVA
  FROM SICAM.HISTORICO_COLETA_STATUS SH;
-- fim ESICAM-729

-- https://jira.machado.com.br/browse/ESICAM-758
ALTER TABLE SICAM.MATERIAL_COLETA ADD TX_HASH_ARQUIVO_RED VARCHAR2(4000) DEFAULT NULL NULL;
COMMENT ON COLUMN SICAM.MATERIAL_COLETA.TX_HASH_ARQUIVO_RED IS 'Armazena o hash md5 do conteúdo da imagem enviada ao RED';

CREATE TABLE SICAM.VERIFICACAO_INCONSISTENCIA (
  NU_VERIFICACAO_INCONSISTENCIA   NUMBER(10)
  GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 NOMINVALUE NOMAXVALUE NOCYCLE NOCACHE NOORDER )
                                                    NOT NULL,
  NU_MATRICULA                    VARCHAR2(12 CHAR) NOT NULL,
  TS_OPERACAO                     TIMESTAMP NOT NULL,
  CO_LOTACAO                      NUMBER(6) NOT NULL,
  NU_INVENTARIO                   NUMBER(10) NOT NULL
);

COMMENT ON TABLE SICAM.VERIFICACAO_INCONSISTENCIA IS
  'Tabela que armazena as verificações de inconsistencias realizadas';

COMMENT ON COLUMN SICAM.VERIFICACAO_INCONSISTENCIA.NU_VERIFICACAO_INCONSISTENCIA IS
  'Codigo chave da tabela, PK Identity identifica o registro unico';

COMMENT ON COLUMN SICAM.VERIFICACAO_INCONSISTENCIA.NU_MATRICULA IS
  'Matricula do responsável pela verificação de inconsistência API_SARH.';

COMMENT ON COLUMN SICAM.VERIFICACAO_INCONSISTENCIA.TS_OPERACAO IS
  'Armazena a data e hora em que a verificação foi realizada';

COMMENT ON COLUMN SICAM.VERIFICACAO_INCONSISTENCIA.CO_LOTACAO IS
  'FK da tabela sarh.lotacao para definir qual a lotação da verificação';

COMMENT ON COLUMN SICAM.VERIFICACAO_INCONSISTENCIA.NU_INVENTARIO IS
  'FK da tabela inventario para definir qual o inventário da verificação';

ALTER TABLE SICAM.VERIFICACAO_INCONSISTENCIA
  ADD CONSTRAINT VERIFICACAO_INCONSISTENCIA_PK PRIMARY KEY ( NU_VERIFICACAO_INCONSISTENCIA );

ALTER TABLE SICAM.VERIFICACAO_INCONSISTENCIA
  ADD CONSTRAINT VERIFICA_INCONSIS_INVENTARI_FK FOREIGN KEY ( NU_INVENTARIO )
REFERENCES SICAM.INVENTARIO ( NU_INVENTARIO );

ALTER TABLE SICAM.VERIFICACAO_INCONSISTENCIA
  ADD CONSTRAINT VERIFICA_INCONSIS_LOTACAO_FK FOREIGN KEY ( CO_LOTACAO )
REFERENCES SARH.LOTACAO ( CO_LOTACAO );


CREATE TABLE SICAM.INCONSISTENCIA (
  NU_INCONSISTENCIA               NUMBER(10)
  GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 NOMINVALUE NOMAXVALUE NOCYCLE NOCACHE NOORDER )
                                                   NOT NULL,
  NU_VERIFICACAO_INCONSISTENCIA   NUMBER NOT NULL,
  TI_INCONSISTENCIA               VARCHAR2(1 CHAR) NOT NULL,
  NU_QUANTIDADE_INCONSISTENCIA    NUMBER(10) NOT NULL
);

ALTER TABLE SICAM.INCONSISTENCIA
  ADD CHECK ( TI_INCONSISTENCIA IN ('C','I','S') );

COMMENT ON TABLE SICAM.INCONSISTENCIA IS
  'Tabela para armazenar as inconsistências encontradas durante uma verificação de inconsistência';

COMMENT ON COLUMN SICAM.INCONSISTENCIA.NU_INCONSISTENCIA IS
  'Codigo chave da tabela, PK Identity identifica o registro unico';

COMMENT ON COLUMN SICAM.INCONSISTENCIA.NU_VERIFICACAO_INCONSISTENCIA IS
  'FK da tabela de verificação de inconsistencia para definir a qual verificação pertence a inconsistência';

COMMENT ON COLUMN SICAM.INCONSISTENCIA.TI_INCONSISTENCIA IS
  'Armazena o tipo da inconsistência encontrado (S=> Situação do bem, C=> estado de Conservacao do bem, I=>Imagem do bem)';

COMMENT ON COLUMN SICAM.INCONSISTENCIA.NU_QUANTIDADE_INCONSISTENCIA IS
  'Armazena a quantidade de inconsistencia encontradas para o determinado tipo';

ALTER TABLE SICAM.INCONSISTENCIA
  ADD CONSTRAINT INCONSISTENCIA_PK PRIMARY KEY ( NU_INCONSISTENCIA, NU_VERIFICACAO_INCONSISTENCIA );

ALTER TABLE SICAM.INCONSISTENCIA
  ADD CONSTRAINT INCONSI_VERIFICACAO_INCONSI_FK FOREIGN KEY ( NU_VERIFICACAO_INCONSISTENCIA )
REFERENCES SICAM.VERIFICACAO_INCONSISTENCIA ( NU_VERIFICACAO_INCONSISTENCIA );


CREATE TABLE SICAM.VERIFICACAO_INCONSIST_COLETA (
  NU_VERIFICACAO_INCONSIS_COLET   NUMBER(10)
  GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 NOMINVALUE NOMAXVALUE NOCYCLE NOCACHE NOORDER )
                                              NOT NULL,
  NU_VERIFICACAO_INCONSISTENCIA    NUMBER(10) NOT NULL,
  NU_COLETA                        NUMBER(10) NOT NULL
);

COMMENT ON TABLE SICAM.VERIFICACAO_INCONSIST_COLETA IS
  'Tabela para armazenar as coletas analizadas na verificação de inconsitência';

COMMENT ON COLUMN SICAM.VERIFICACAO_INCONSIST_COLETA.NU_VERIFICACAO_INCONSIS_COLET IS
  'Codigo chave da tabela, PK Identity identifica o registro unico';

COMMENT ON COLUMN SICAM.VERIFICACAO_INCONSIST_COLETA.NU_VERIFICACAO_INCONSISTENCIA IS
  'FK da tabela de verificação de inconsistência';

COMMENT ON COLUMN SICAM.VERIFICACAO_INCONSIST_COLETA.NU_COLETA IS
  'FK da tabela de coletas para determinar as coletas utilizadas em uma verificação de inconsistência';

ALTER TABLE SICAM.VERIFICACAO_INCONSIST_COLETA
  ADD CONSTRAINT VERIFICACAO_INCONSIS_COLETA_PK PRIMARY KEY ( NU_VERIFICACAO_INCONSIS_COLET );

ALTER TABLE SICAM.VERIFICACAO_INCONSIST_COLETA
  ADD CONSTRAINT VERIFICACAO_INCONSIS_COLET__UN UNIQUE ( NU_VERIFICACAO_INCONSISTENCIA, NU_COLETA );

ALTER TABLE SICAM.VERIFICACAO_INCONSIST_COLETA
  ADD CONSTRAINT VERIFI_INC_COL_COLETA_FK FOREIGN KEY ( NU_COLETA )
REFERENCES SICAM.COLETA ( NU_COLETA );

ALTER TABLE SICAM.VERIFICACAO_INCONSIST_COLETA
  ADD CONSTRAINT VERIFI_INC_COL_VERIFI_INC_FK FOREIGN KEY ( NU_VERIFICACAO_INCONSISTENCIA )
REFERENCES SICAM.VERIFICACAO_INCONSISTENCIA ( NU_VERIFICACAO_INCONSISTENCIA );
-- fim ESICAM-758