<?php

namespace Tests\Integration;

use Illuminate\Contracts\Console\Kernel;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class IntegrationTestCase extends BaseTestCase
{
    protected function setUp()
    {
        parent::setUp();
        $databaseFilePath = config('database.connections.sqlite.database');
        $databaseFilePathBkp = $databaseFilePath . '.bkp';

        if (file_exists($databaseFilePath)) {
            unlink($databaseFilePath);
        }

        if (file_exists($databaseFilePathBkp)) {
            copy(
                $databaseFilePathBkp,
                $databaseFilePath
            );
            return;
        }

        touch($databaseFilePath);
        $this->artisan('migrate:refresh');
        $this->artisan('db:seed');
        copy(
            $databaseFilePath,
            $databaseFilePathBkp
        );
    }

    protected function tearDown()
    {
        unlink(config('database.connections.sqlite.database'));
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function createApplication()
    {
        $app = require __DIR__.'/../../bootstrap/app.php';

        $app->make(Kernel::class)->bootstrap();

        return $app;
    }

    public function getPaginateStructure($dataStructure = [])
    {
        return [
            'current_page',
            'data' => $dataStructure,
            'total',
            'per_page',
            'path',
            'from',
        ];
    }

    public function post($uri, array $data = [], array $headers = [])
    {
        $headers['Accept'] = 'application/json';
        return parent::post($uri, $data, $headers);
    }

    public function put($uri, array $data = [], array $headers = [])
    {
        $headers['Accept'] = 'application/json';
        return parent::put($uri, $data, $headers);
    }
}
